### ISSUE TITLE
bug: insert into is too slow

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#10768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.0.26-nightly-d9b7f4a8080b54d2b4c4a515296ee7557fc135f1(rust-1.70.0-nightly-2023-03-21T04:38:53.365198122Z)

deploy mode is single

### What's Wrong?

CREATE TABLE `car_location_11` (
  `id` BIGINT NULL COMMENT '主键ID',
  `source_id` VARCHAR NULL COMMENT '原始数据id',
  `car_number` VARCHAR NULL COMMENT '车牌号',
  `acc` VARCHAR NULL COMMENT 'Acc状态:1开 0关',
  `status` TINYINT NULL COMMENT '车辆状态: 1=行车在线 2=停车在线 3=车辆离线',
  `lon` DOUBLE NULL COMMENT '经度',
  `lat` DOUBLE NULL COMMENT '纬度',
  `speed` INT NULL COMMENT '速度',
  `direction` INT NULL COMMENT '方向',
  `altitude` INT NULL COMMENT '海拔高度',
  `occurrence_time` TIMESTAMP NULL COMMENT '信息发生时间',
  `gmt_create` TIMESTAMP NULL COMMENT '创建时间',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间'
);
the insert data file is:
[gtransport.car_location_11.0000000000024.zip](https://github.com/datafuselabs/databend/files/11067880/gtransport.car_location_11.0000000000024.zip)

execute by Mysql Client :mysql -uroot -pLenovo@@7788 -h192.168.10.11 -P3306 < /tmp/export_create_data_sql/gtransport.car_location_11.0000000000007.sql

if insert into mysql, only cost less 2 seconds
but insert into databend,it cost more than 25 seconds

i wonder why databend cost so much time? 

**and another problem is:
the data size  in mysql  is 2G,but when i insert into databend, it becomes 100G**

now i am syncing data from mysql to databend by sql file,hope someone can help me.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
The SQL INSERT statement with a small VALUES batch size can be slow. Consider increasing the batch size to, for example, 1,000,000 rows per batch to improve performance. However, in Databend, it is generally more efficient to use the COPY command instead of `INSERT`. You can find more information about the `COPY` command here: https://databend.rs/doc/sql-commands/dml/dml-copy-into-table

**Comment by dantengsky** [comment]
> if insert into mysql, only cost less 2 seconds but insert into databend,it cost more than 25 seconds


please consider batch loading:

https://docs.databend.cn/load-transform-data/


> **and another problem is: the data size in mysql is 2G,but when i insert into databend, it becomes 100G**

 for each insert statement, a historical version of table will be kept, which takes space, try `optimize table t purge`
 


> now i am syncing data from mysql to databend by sql file,hope someone can help me.

@wubx  may have further suggestions?

**Comment by wubx** [comment]
1. Insert is not a Databend best practice 
2. Insert data become big, This is due to the Databend Time Travel feature. You can disable it, create transient table car_location_11(...), It's will small and fast.  https://databend.rs/doc/sql-commands/ddl/table/ddl-create-table#create-transient-table
3. Load MySQL to Databend best practices you TiDB dumpling dump mysql to csv | tsv, later use copy into load it to Databend

**Comment by wubx** [comment]
Please add My WxChat: 82565387  
Let's take a private conversion.
