### ISSUE TITLE
bug: Parsing limit clause failed,  Create table xxx as (select ... limit x)

### ISSUE THREAD

**Issue by mokeyish** [datafuselabs/databend#11004]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

commit id: [434fe3d](https://github.com/datafuselabs/databend/commit/434fe3dc02dc19b137dca971b5d2a51e0a52b9ef)

### What's Wrong?

Parsing `limit` clause failed when use `create table xxx as <subquery limit x>`.

### How to Reproduce?

```rust
#[test]
fn test(){
    let sql = r#"
    create table abc as (
        select * from xyz limit 10
    )
    "#;
    let sql_tokens = super::parser::tokenize_sql(sql).unwrap();
    let (s, _) = super::parser::parse_sql(&sql_tokens, Default::default()).unwrap();
    println!("{:#?}", s);
}
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
no `()`.

query should like this:

```sql
create table ac as select * from xyz limit 10;
```

reference : https://databend.rs/doc/sql-commands/ddl/table/ddl-create-table#create-table--as

**Comment by mokeyish** [comment]
But this `create table abc as ((select * from xyz))` works. Should we support it?remove the unneccessary brackets automatically.

**Comment by mokeyish** [comment]
I've fix it by:

![图片](https://user-images.githubusercontent.com/16131917/230878089-a111d63b-a0d4-4abb-aa9f-6718623a601b.png)

**Comment by mokeyish** [comment]
It conflicts the parsing with other parts.

**Comment by TCeason** [comment]
cc @andylokandy

**Comment by andylokandy** [comment]
This problem was raised in the following GitHub pull request: https://github.com/datafuselabs/databend/pull/10820. The issue addressed the exponential complexity of handling subquery parentheses. After discussions and benchmarks, we concluded that enforcing exactly one parenthesis for the subquery would be best. However, we overlooked the fact that the `create .. as select ..` statement should actually be written as `create ... as (select ..)`. We can enforce this syntax - what are your thoughts on this solution?
