### ISSUE TITLE
Feature: hope  to support view use "show full COLUMNS from view_xx form xx"

### ISSUE THREAD

**Issue by zhoukai-1992** [datafuselabs/databend#11136]
use view can not show COLUMNS .
There is no problem with the display in mysql view
![image](https://user-images.githubusercontent.com/83740823/233067533-4cb18291-ce59-443d-94b1-e049486e6e48.png)
There is no problem with the display in table
![image](https://user-images.githubusercontent.com/83740823/233067885-ce8cc90c-a15c-48b5-8a47-7947c0e5d712.png)
![image](https://user-images.githubusercontent.com/83740823/233068049-a77d502a-830d-4730-8f04-ab083aa7971d.png)

**Comment by TCeason** [comment]
Now show columns will read data from information_schema.columns and the data in this table is from system.columns.

Because of this issue: https://github.com/datafuselabs/databend/issues/10632, the system.columns filter view engine fields.

If this is necessary, we will refactor the show columns interpreter.
