### ISSUE TITLE
bug: memory leak in unsafe code

### ISSUE THREAD

**Issue by SkyFan2002** [datafuselabs/databend#12445]
**Summary**
https://github.com/datafuselabs/databend/blob/b6cb56baa276b9c0c794fd83ec3851eeba5c0252/src/query/expression/src/block.rs#L90-L114
The memory is not freed after `Box::into_raw()`

**Comment by BohuTANG** [comment]
AskGPT:
does the code have a memory leak?

Yes, the code snippet you posted has a potential memory leak in the `downcast_from` method. Let's analyze the relevant portion of the code:

```rust
if boxed.as_any().is::<T>() {
    unsafe {
        // SAFETY: `is` ensures this type cast is correct
        let raw_ptr = Box::into_raw(boxed) as *const dyn BlockMetaInfo;
        return Some(std::ptr::read(raw_ptr as *const Self));
    }
}
```

Here's what happens:

1. You're using `Box::into_raw(boxed)`, which converts the boxed value into a raw pointer. This means that Rust's ownership system no longer tracks this value, and you're responsible for deallocating it.
2. You then cast this raw pointer to another type and read the value from it using `std::ptr::read`. This function reads the value without advancing the pointer or deallocating the memory.
3. You return the value wrapped in `Some`, but you never deallocate the memory that was originally allocated for the boxed value.

The proper way to handle this would be to use `Box::from_raw` after the cast, allowing the `Box` to take ownership again, and then dereferencing the box to obtain the value. Here's a corrected version of that part:

```rust
if boxed.as_any().is::<T>() {
    unsafe {
        // SAFETY: `is` ensures this type cast is correct
        let raw_ptr = Box::into_raw(boxed) as *mut dyn BlockMetaInfo;
        let typed_ptr = raw_ptr as *mut Self;
        return Some(*Box::from_raw(typed_ptr));
    }
}
```

Notice that I changed the pointer to a mutable one (`*mut` instead of `*const`) because `Box::from_raw` expects a mutable raw pointer. This corrected version properly deallocates the memory and avoids the leak.
