### ISSUE TITLE
Pip install in colab, still on an old version

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

python

### What's Wrong?

![image](https://github.com/datafuselabs/databend/assets/12554469/039dddd6-e70f-4d77-be96-ed6544b28f35)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
This because the space of pipy is full: [see here](https://github.com/datafuselabs/databend/actions/runs/5928690137/job/16078955574), we have clean the room(By @sundy-li ) and publish a new release:
https://github.com/datafuselabs/databend/releases/tag/v1.2.79-nightly

You can try it again if all the actions is ok here:
https://github.com/datafuselabs/databend/actions/runs/5940312601
