### ISSUE TITLE
feat: remove XML InputFormat.

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#13460]
**Summary**

no standard way for XML to carry table data.
even Clickhouse, which has lots of formats, only use XML for outputs.

**Comment by youngsofun** [comment]
cc @Xuanwo for https://github.com/datafuselabs/databend/issues/7656
cc @wubx

**Comment by Xuanwo** [comment]
> no standard way for XML to carry table data.

Makes sense. Let's do this.

**Comment by youngsofun** [comment]
but snowflake support it https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#type-xml
https://medium.com/snowflake/working-with-xml-in-snowflake-part-i-8b4eca1c01fa
https://community.snowflake.com/s/article/HOW-TO-QUERY-NESTED-XML-DATA-IN-SNOWFLAKE

**Comment by youngsofun** [comment]
let`s remove the current XML input format. and make XML a type on top of JSON varaint.

**Comment by Xuanwo** [comment]
Thanks!

**Comment by youngsofun** [comment]
@drmingdrmer 

I want to remove code about XML input format,  and may add a brand new one later (I guess not until user really require it)

there are 2 choices:
1.  keep XmlFileFormatParams xml = 6,  when new XML, add new fields in XmlFileFormatParams 
2.  remove them totally, may add  XmlFileFormatParams xml = 7, later

which do you perfer?
what should I do with the related codes in proto, proto-conv, and the tests, separately?

```
message FileFormatParams {
  oneof format {
    ParquetFileFormatParams parquet = 1;
    CsvFileFormatParams csv = 2;
    TsvFileFormatParams tsv = 3;
    JsonFileFormatParams json = 4;
    NdJsonFileFormatParams nd_json = 5;
    XmlFileFormatParams xml = 6;
  }
}
```

```
message XmlFileFormatParams {
  uint64 ver = 100;
  uint64 min_reader_ver = 101;
  StageFileCompression compression = 1;
  string row_tag = 2;
}

```

**Comment by drmingdrmer** [comment]
Remove them entirely.

The approach of removing and then adding is generally preferred because these types of modifications are natively backward compatible. On the other hand, making changes to a structure often requires manual handling to maintain compatibility.

When removing a field, mark it as `reserved`, so that no new field using this field index and compatibility will be held.
https://protobuf.dev/programming-guides/proto3/#fieldreserved

The work to support this change includes:
- add a new message type to proto files,
- add a corresponding rust type for the new protobuf message,
- impl `FromToProto` for these two new types,
- Add a new change-log record to `util.rs`, and add a new compatibility test: https://github.com/drmingdrmer/databend/blob/1a469e5540bf2c57aa0cf7f76117d5267febe195/src/meta/proto-conv/src/util.rs#L122

**Comment by drmingdrmer** [comment]
Hmm... I was not totally right in my earlier statement.

Both approaches you've outlined involve just simple additions or removals, which makes them equally preferable from a technical standpoint.

However, if the intention is to remove a type, opting for removal alone would clearly express the purpose of the change, making it a more straightforward choice.
