### ISSUE TITLE
[improvement]Double quotation marks are supported in arguments

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#1551]
**Summary**
Please support double quottion marks for ident.

Description for this improvement.

show tables where name = 'a';
+------+
| name |
+------+
| a    |
+------+
Run ok。 

but 
mysql> show tables where name="a";
ERROR 1105 (HY000): Code: 6, displayText = Unable to get field named "a". Valid fields: ["database", "name"].

**Comment by leiysky** [comment]
The root cause of this issue is that `sqlparser-rs` will parse double quoted `"a"` into a `Identifier` with `GenericDialect`, while it should be a `Value` in semantic.

In PostgreSQL, identifiers are double quoted like **"ident"**, and in MySQL they are back quoted like **\`ident\`**.

To distinguish between them, there should be a mechanism to make a hole in AST(keep the original token), and translate it into AST node with dialect information right after the initial parsing.

We can evaluate this in our new parser design.
