### ISSUE TITLE
[feature] partition/file pruning by indexing

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1552]
**Summary**

Impl the `apply_index` against the expression.

**Comment by leiysky** [comment]
I have a plan on expressions normalization in #1539 , in purpose of providing ability to do complicated partition pruning(e.g. rewrite `a + 1 < 2` to `a < 1` so we can directly apply the comparison on partition key).

By the way, it's a very big challeng to do partition prune in a data warehouse, since there may be a large amout of partitions in a single table(says millions), which can bring serious burden to optimizer. The mainstream data warehouse(e.g. Snowflake) has a mechanism like intermidiate partition to reduce the metadata should be read during query optimization.

We can have a more robust design on this in the future.

**Comment by BohuTANG** [comment]
@leiysky 
That's interesting.
Datafuse supports 3-level partition pruning to fast query(Which ClickHouse did, simply and efficiently), there is a introduce in:
https://github.com/datafuselabs/datafuse/blob/master/common/indexing/README.md

The apply index patch will be launched next week.

**Comment by zhyass** [comment]
Tasks to be done:
- [x] Add verfiable expression.
- [ ] Apply to TableSparseIndex.
- [ ] Support like/not like.
- [ ] Add monotonic check in FunctionFactory.
