### ISSUE TITLE
[improvement] refine the datasources

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1802]
**Summary**

Consider refine the datasources as:

```
-| datasources
  -| index // for indexing
  -| common // for util common
  -| table // for fuse table impl
  -| dal // disk access layer(dal)
  -| datasource
     -| local  // Local database datasource
     -| system // System database datasource
     -| remote // Remote database datasource
```

- [x] move common/dal and common/indexing to datasources 
     issue #1804
- [x] #1805
- [x] #1806
       Let's re-consider this, maybe we should do this in latter iterations
- [x] #1807
- [x] #1812

**Comment by BohuTANG** [comment]
cc @dantengsky 
Comments always are welcome :thought_balloon:

**Comment by dantengsky** [comment]
- does it mean that we are going to move `common/{idx, dal}` into `query/src`?

  If it does, I am okay with it since no other crates depending on these components at present.

- As for the `datasource`

I do have the same feeling that the current dir layout

    ```
     -| datasources
       -| fuse_table
       -| local
       -| remote
    ```
    
  is confusing, since `fuse_table` is NOT a database engine.
    
but I suggest the following layout
 
```
 -| datasources
   -| csv          // for CSV format, implementation are free to support DAL or not
   -| tsv           // for TSV
   -| parquet // for parquet
   -| vtables  // for system db tables
   -| fuse        // fuse table
   -| table.rs  // we may sepreate the concepts of datasource and table later, at present, all DS are table relations
   -| table_registry.rs // all table engines register themselves here
   -| table_provider.rs // the factory, creates tables by engine type and table options
 -| database_engines
   -| default_db.rs // default database, which delegates requests to `MetaBackend`
   -| mysql_db.rs  // table metas are fetched from a MySQL database
   -| sys_db.rs        // vtables, read only
   -| information_schema_db.rs // vtables read only
   -| xxxx_db.rs
   -| db_registry.rs // all db engines register themselves here
   -| db_provider.rs // the factory, creates instances of Dataase Trait by engine type and database options
```

The idea behind this is :

Imagine that,  later, a user may want to create a `TSV/CSV` table in the `remote` database, such that, user can extract/transform/load data into a `fuse` table.

Note that, a local table may not fit the requirement, since data ingestion may be executed distributedly,  all query nodes should be able to know the source table, thus 1.) the local database could not meet the requirement 2.) we might need to support different table engines in one database engine

Besides, I am not sure about the benefits of the **co-existence** of the "Remote" and "Local" databases **at runtime** yet, IMHO, a single backend seems to be enough (except for unit testing),  or, to put it more precisely, there should be only one instance of "MetaBackend" at runtime.  pls correct me if I misunderstood anything.


pseudo code snippet

~~~~

// Only need table meta

let table_meta: PureMeta = catalog.get_table(db, tbl)?;

// behind the scene
// ACatalog::get_table(...) -> Result<TableMeta> {
//    self.meta_backend.get_table_meta(db_name, tbl_name)?
// }

// later, we need Table/Datasource Trait later

let table = table_provider.table(tabel_meta);

// behind the scene
// table_provider::table(table_meta) -> Result<Arc<dyn Table>> {
//   let provider =  self.table_registry.get_provider(table_meta.engine_type)?;
//   provider.try_create(table_meta.table_options)
// }

~~~~

This code snippet over-simplified too many things, definitely naive.  anyway, hope it could bring some inspiration.
