### ISSUE TITLE
`Table::read_plan` is not in data path. Make it sync or async?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2181]
`Table::read_plan` may take a long time to access underlying data(local fs or remote s3) to fetch part list.
Consider making it an `async` method or leave it as is?

> In the current impl, FuseTable::read_plan need to access sparse index and other statistics to build a well partitioned plan, through DataAccessor, which is backed by LocalFS or S3.
> 
> If reading-index is considered as the data-path, making read_plan an async method would be better.

> shall we change the signature of `Table::read_plan` from sync to async? plan parser using this method while creating relation

Actually, read_plan is not in data path, change it to async looks not make sense.
In data path, we may wait some block data to transfer between disk(io) or rpc(network), use async looks more make sense.

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/2062#issuecomment-936244791_

**Comment by drmingdrmer** [comment]
@dantengsky

**Comment by drmingdrmer** [comment]
All right guys. One less thing off the TODO-list, 😆

**Comment by leiysky** [comment]
It's expected that we won't take parallelism as a variable factor in our cost model for a long time, which means we don't actually need the information about physical distribution of a table during planning. Therefore, `Table::read_plan` will only be invoked by scheduler to determine the way to read from a table.

I think you can just ignore planner for this issue, since @sundy-li is trying to move `Table::read_plan` outside `PlanParser` if I remember correctly.
