### ISSUE TITLE
meta_embedded_dir is a test purpose path, it would be better to set it as a random uuid instead config it in the tomorrow config file?

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2535]
**Summary**

https://github.com/datafuselabs/databend/pull/2534#discussion_r739584995

**Comment by drmingdrmer** [comment]
Not very sure about if it's just for test.

@sundy-li 🤔

**Comment by drmingdrmer** [comment]
If it is just for test, the current impl is good: embedded meta is always stored in a `temp` dir.

Otherwise, `query` need to initialize a global `sled` db when starting up as metasrv does:
https://github.com/datafuselabs/databend/blob/c02796f43a64a507467fb63594c7c79836c58974/metasrv/src/bin/metasrv.rs#L51

**Comment by sundy-li** [comment]
Yes, currently is enough.

**Comment by drmingdrmer** [comment]
The tmp dir will be removed when `query` process exit.
Is that still all right?

**Comment by sundy-li** [comment]
> The tmp dir will be removed when query process exit.

I don't think we should have the remove codes inside databend-query. We let user know that temp directory is in `/tmp/databend`, users can decide to remove it or not.

**Comment by BohuTANG** [comment]
Found that `meta_embedded_dir` https://github.com/datafuselabs/databend/blob/c02796f43a64a507467fb63594c7c79836c58974/query/src/configs/config_meta.rs#L33-L36 is not used by any others, why we introduce it here? cc @drmingdrmer

**Comment by drmingdrmer** [comment]
It is just meant to specify the path to store embedded meta store.

But `init_sled_db(config.meta_embedded_dir)` will just fail some unit tests. Every unit test need a unique value of `meta_embedded_dir` to avoid conflict.

That's why in that PR I did not use it and just always create a random tmp dir for embedded meta store.

In order to actually use it, `databend-query` has to init the sled db in `meta_embedded_dir` and a unit test has to init sled db in a random tmp dir.
This might IMO introduce some work of re-organizing the `query` startup procedure thus had been left to some other PR. 🤔

**Comment by BohuTANG** [comment]
OK.
meta_embedded_dir is only setting when we run databend-query itself without the databend-meta service, now it's ONLY the test purpose for databend-query, so, I preferred this config field not show in the config file let the user confused and pain it🙂

**Comment by sundy-li** [comment]
I think we should have this config  but we can merge this config with `meta_address`.

For databend-query, it needs a meta-service but it does not care which specific meta-service provider is(embedded_meta or remote_meta).

Consider this case:

Some user(just like the author of https://tech.marksblogg.com/benchmarks.html ) wants to test databend's single node query performance, so he will try to start databend-query in embedded mode.

Then he will load some large test data into databend, but he will soon notice that it defaults to store data in `/tmp` yet it has no enough space even more he can't modify the `meta_embedded_dir ` because we don't export it in config.

**Comment by drmingdrmer** [comment]
Something like this? A single url to define where it is:

```toml
# remote:
meta_store = "flight://root:passwd@127.0.0.1:9999"
# local:
meta_store = "file://./_meta_embedded"
```

**Comment by BohuTANG** [comment]
Outdated.
