### ISSUE TITLE
angles function not support NULL input like MySQL

### ISSUE THREAD

**Issue by pymongo** [datafuselabs/databend#2844]
**Summary**

databend:

```
MySQL [(none)]> SELECT RADIANS(NULL);
ERROR 1105 (HY000): Code: 7, displayText = Expected numeric, but got Null.
```

MySQL:

```
MariaDB [(none)]> SELECT RADIANS(NULL);
+---------------+
| RADIANS(NULL) |
+---------------+
|          NULL |
+---------------+
```

**How to reproduce**

> SELECT RADIANS(NULL);

**Additional context**

https://github.com/datafuselabs/databend/blob/a4781bf3cff6286caf30200eddbe9f3648ad9e06/common/functions/src/scalars/maths/angle.rs#L66

angle function source code not support NULL input

**Comment by flaneur2020** [comment]
besides the type check in the `return_value()` function, here'd raise an error on casting a NULL array to a float64 array:

https://github.com/datafuselabs/databend/blob/a4781bf3cff6286caf30200eddbe9f3648ad9e06/common/functions/src/scalars/maths/angle.rs#L84

because the arrow2 version we're using hasn't include the NULL casting logic yet, after cherry-picking this PR from arrow2 https://github.com/jorgecarleitao/arrow2/pull/589 , this casting error could be suppressed.

**Comment by BohuTANG** [comment]
> besides the type check in the `return_value()` function, here'd raise an error on casting a NULL array to a float64 array:
> 
> https://github.com/datafuselabs/databend/blob/a4781bf3cff6286caf30200eddbe9f3648ad9e06/common/functions/src/scalars/maths/angle.rs#L84
> 
> casting a NULL array to a float64 array is legal in the arrow semantics, because all the array element in arrow are nullable
> 
> but the arrow2 version we're using hasn't include the NULL casting logic yet, after cherry-picking this PR from arrow2 [jorgecarleitao/arrow2#589](https://github.com/jorgecarleitao/arrow2/pull/589) , this casting error could be suppressed.

https://github.com/datafuse-extras/arrow2 has updated with the upstream

**Comment by flaneur2020** [comment]
> Maybe all of the functions we should support DataType::Null ?

I think so 🤔
