### ISSUE TITLE
it'd prefered to stored as a ordered flat kv format, like

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2957]
it'd prefered to stored as a ordered flat kv format, like

```
(user, host, database, table) -> privilege_set
```

so we can list an user's grants in a prefix scan, and can drop a grant individually.

but in the eariler days, a big `GrantSet` json is easier to implement,

```
user -> GrantSet
```

and it would not get very big in the near future (i cant imagine how to manage a 20+ grants configs🤔)

the cons of the big JSON is that we have to deserialize the object, make modifications, and write back.

_Originally posted by @flaneur2020 in https://github.com/datafuselabs/databend/issues/2894#issuecomment-975153594_

**Comment by RinChanNOWWW** [comment]
Hello @drmingdrmer , I'm interested in this issue. Is this issue is still needed to solve? If so, I have some question about it:

1. A user's privilege information is store with other information like auth info, so we need to store priviledge information and other information separately?
2. What about the `RoleInfo`? Should we flatten it too? Like: (role, database, table) -> privilege_set (Current: role -> GrantSet).
3. Backward compatibility. How to deal with the old format.
4. How to format the key.

**Comment by drmingdrmer** [comment]
@flaneur2020 
Is the requirement of privilege still like this issue described?

**Comment by RinChanNOWWW** [comment]
PTAL @flaneur2020

**Comment by flaneur2020** [comment]
sorry for the late response, in my opinion the works on keep backwards compatibility with this refactor is pretty big, it might requires some careful design and a roadmap to migrate in a backward compatible manner.

I guess we can keep this status not changed in the short term, and reopen this issue if we found it profitable to make this change.

**Comment by Xuanwo** [comment]
> I guess we can keep this status not changed in the short term, and reopen this issue if we found it profitable to make this refactor.

Agreed.

Let's close.
