### ISSUE TITLE
`CREATE TABLE table AS SELECT ...` statement

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3216]
**Summary**

Create a table by selecting from an existing table (schema and data):
```
mysql> create table t1(a int);


mysql> insert into t1 values(1),(2);

mysql> create table t2 as select * from t1;

mysql> select * from t1;
+------+
| a    |
+------+
|    1 |
|    2 |
+------+

mysql> select * from t2;
+------+
| a    |
+------+
|    1 |
|    2 |
+------+

```

Reference:
https://dev.mysql.com/doc/refman/8.0/en/create-table-select.html

**Comment by AngleNet** [comment]
@BohuTANG I am new to databend. I would like to help on this. Could you assign it to me ?

**Comment by dantengsky** [comment]
@BohuTANG 


the `atomic DDL` semantics that `https://dev.mysql.com/doc/refman/8.0/en/create-table-select.html` describe might be hard to be implemented in one go, shall we relax them somehow?

IMO, we may implement the non-atomic version first. since there is no "tmp" catalog yet, and the execution of `insert ... as select` assumes that the `catalog` is aware of the table that is being inserted, it might be hard to implement this semantic(if not impossible, for the time being).
   
a rough idea goes like this (for `create table t2 as select * from t1`):

   1). inspects the schema of the table `t2` that is being crated
    since the tables of sub-clause `select ....`  should already exist, the schema of the `select` plan could be inferred.
   2) create the table `t2` by using `catalog` API
   3) insert the table (for example, by executing the  plan of  `insert into t2 select * from t1`)
   
we **allow** that if anything goes wrong between 2) and 3), there might be an empty table left (in meta-server)

**Comment by BohuTANG** [comment]
@dantengsky 
I agree with you.
'IMO, we may implement the non-atomic version first.'
We could make it work first, then make it right.

**Comment by dantengsky** [comment]
Hi @AngleNet, hope the above discussion be helpful :)

**Comment by AngleNet** [comment]
> helpful

Thank you for clarify this. I'm still working on supporting syntax of 'create table as select'.  I split it as some small tasks to be finished: 

- [ ] Support 'create table as select' syntax
- [ ] Infer schema of new table from select statement
- [ ] Insert rows of select statement to the new table

The PR will be released later.
