### ISSUE TITLE
ERROR 1105 (HY000): Code: 10, displayText = AggregateSumFunction does not support type 'Boolean' (while in select group by).

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3383]
**Summary**

```
mysql> select avg(number>10) from numbers(100);
ERROR 1105 (HY000): Code: 10, displayText = AggregateSumFunction does not support type 'Boolean' (while in select group by).

```

**Comment by zhang2014** [comment]
related: https://github.com/datafuselabs/databend/discussions/3267

**Comment by everpcpc** [comment]
MySQL does not have a builtin boolean type actually, maybe it is OK to change all boolean response here to a `u8`?

**Comment by sundy-li** [comment]
> MySQL does not have a builtin boolean type actually, maybe it is OK to change all boolean result here to a u8?

Some database systems take `boolean` as the alias of `u8`, eg: `ClickHouse`, `doris-vectorized` ...

Though  `bitmap` compared to  `Vec<u8>`, it saves memory spaces by 8 times, its performance may not be better than `Vec<u8>`. Because computers do not operate on bits. The memory bus is byte-addressed, and processors operate on register words, which are typically four to eight bytes, or even wider.

From a storage perspective,  if we use a good compression algorithm (lz4, zstd), both`bitmap` & `Vec<u8>` can reach well compression ratio.

But since we use arrow system, so if we change boolean to u8, there may be some more work we need to refactor, such as :
1.  `DataBlock::filter` or other ops.
2.  Extra memory cost from databend's `Vec<u8>` to arrow's `Bitmap` (null validity) vice versa.
