### ISSUE TITLE
Change auth_type to password_type.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3480]
**Summary**

Task of #3476

**Comment by youngsofun** [comment]
@BohuTANG  

after discussing with @flaneur2020, I think we should change password_type back to auth_type.
and use the same field to hold enum { JTW,  Sha256Password, DoubleSha1Password, ...},   which directly corresponds to the "With" part in SQL.

otherwise, we need another field to hold enum {JWT, Password, },  which is a waste and has no benefit.
