### ISSUE TITLE
bug: `select a, b from (select cast(1 AS String) as a, cast(2 AS String) as b) group by a,b` broken

### ISSUE THREAD

**Issue by ives9638** [datafuselabs/databend#3629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

select a ,b ,count() from (select cast( (number%4) AS VARCHAR) as a,  cast( (number%20) AS VARCHAR) as b from numbers(100)) group by a ,b  limit 1 ;
+------+------+---------+
| a    | b    | count() |
+------+------+---------+
| 113 | 13  |       5 |
+------+------+---------+

### What You Expected?

 see Result A is bug ?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
I believe it's related to `group by String`, cc @zhang2014 ?

**Comment by ygf11** [comment]
I think the issue is in transform_group_by_final execute.
https://github.com/datafuselabs/databend/blob/1df029427b04006cf467e4f21f168a8fb13c9043/query/src/pipelines/transforms/transform_group_by_final.rs#L210-L213 

I print before and after `de_group_columns`, find the before is correct, like:
```
[[1, 51, 2, 49, 53], [1, 48, 2, 49, 54],...]
```

For `[1, 51, 2, 49, 53]`, the meaning is:
```
a  b
3  15
```
so the result of serialize is correct, but the final output is wrong.

**Comment by sundy-li** [comment]
My bad, not related to `bincode`.
