### ISSUE TITLE
Improvement: Consider caching object(instead of bytes) in in-memory cache

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#3751]
For the cache in storage, it would be better if we could eliminate the de-serialization operation while reading cached item from cache

https://github.com/datafuselabs/databend/blob/a0190843ccfd1190b6e11b22e7ea08a32944d2ae/query/src/storages/fuse/io/meta_reader.rs#L27-L40

**Comment by BohuTANG** [comment]
Good.


Found some places prefered use funtion instead of object in storage, likes:
1.  `read_obj` we use `cache` as a para.

2. Another place is:
```
#[tracing::instrument(level = "debug", skip(table_snapshot, schema, push_down, data_accessor, ctx), fields(ctx.id = ctx.get_id().as_str()))]
pub async fn apply_block_pruning(
    table_snapshot: &TableSnapshot,
    schema: DataSchemaRef,
    push_down: &Option<Extras>,
    data_accessor: Arc<dyn DataAccessor>,
    ctx: Arc<QueryContext>,
) -> Result<Vec<BlockMeta>> {
    BlockPruner::new(table_snapshot, data_accessor)
        .apply(schema, push_down, ctx)
        .await
}
```


`cache` and `ctx(QueryContext)` is global, is it possbile to embed them when the storage created?
```create(ctx, cache ....)```

And we won't give them as a parameter to the function when calling, this looks more objective :)
