### ISSUE TITLE
Feature: add /v1/status uri to show real time tenant, cluster, S3, and latest query endtime status

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4354]
**Summary**
It would be nice to have it for management and debugging

**Comment by ZhiHanZ** [comment]
cc @youngsofun , do you want to take this issue?

**Comment by flaneur2020** [comment]
we can also consider adding a field into the /api/v1/health handler:

https://github.com/datafuselabs/databend/blob/main/query/src/api/http/v1/health.rs#L20

**Comment by flaneur2020** [comment]
we can also consider adding a field into the /api/v1/health handler:

https://github.com/datafuselabs/databend/blob/main/query/src/api/http/v1/health.rs#L20

**Comment by youngsofun** [comment]
cluster_id is directly for from config.
tenant also from config, can only change in for  a session

can wait for they can be update？
maybe we need a global setting/context, instead of construct everything from conf directly

---

 last queried time is ok
 can store it as an atomic in global session_manager (maybe in global setting/context later)
 so /api/v1/health is will not fail or block.

and I can return durion since ` last queried time`  to avoid problem of client diff clock time
@flaneur2020
