### ISSUE TITLE
Feature: Adapt to different countries support user change timezone

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4651]
**Summary**

Support databend-query setting the global timezone， To adapt to different countries.

if the user not setting the timezone make it follow the os system.

**Comment by BohuTANG** [comment]
This is a global session setting(work in progress, https://github.com/datafuselabs/databend/issues/3933).
Default should be UTC not the system timezone.
See https://docs.snowflake.com/en/sql-reference/parameters.html#timezone

**Comment by wubx** [comment]
Learn from Snowflake that their timezone is just a session setting.

```
Type
Session — Can be set for Account » User » Session

Data Type
String (Constant)
```
Maybe session setting is enough.

**Comment by Veeupup** [comment]
This feature may have a lot of changes with functions and query files (hundreds of files), because we need to pass the parameter `timezone` from `query` to `functions`. And in the same time, we need to change the logical of date functions, so we need to change it into smaller tasks to make it.

- [ ] pass parameter from `QueryContext` to `FunctionContext` (for now, only for`timezone`)
- [ ] add session setting of timezone
- [ ] modify date functions logic and add more stateless test
