### ISSUE TITLE
bug: insert into json_test select * from json_test panic the databend-query

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

 insert into json_test select * from json_test panic the databend-query

### What You Expected?

N/A

### How to Reproduce?

Deploy Databend with s3.

Table:
``` 
CREATE TABLE `json_test` (
  `a` Variant,
);
```

Insert a value:
```
insert into json_test values('{"aa":1,"aA":2,"Aa":3}');
```
Then do many times:
```
 insert into json_test select * from json_test;
```

When the count is :
```
mysql> select count(*) from json_test;
+----------+
| count()  |
+----------+
| 67108864 |
+----------+
```

If we do:
```
 insert into json_test select * from json_test;
```

The databend-query will exit with no error message.

Server log:
```
[[2m2022-04-09T11:56:27.754587Z^[[0m ^[[32m INFO^[[0m ^[[2mdatabend_query::servers::mysql::mysql_interactive_worker^[[0m^[[2m:^[[0m the not matched query is insert into json_test select * from json_test
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by b41sh** [comment]
I tested this case, it will return normally when the amount of rows is relatively small. When the amount of rows reaches 67108864, the data will eventually be returned, but the response time is very long, about more than half an hour. The reason is that the JSON data needs to be parsed every time the data is read. I think this is a performance issue rather than a bug. We need to use some binary JSON encoding format to speed up JSON parsing.

**Comment by sundy-li** [comment]
We can use perf to get the bottleneck of this query.
https://github.com/datafuselabs/databend/blob/01a0053e04b979b9a64a2f9c3a7ff98ab1142a5a/docs/doc/100-faq/30-how-to-profiling.md

**Comment by BohuTANG** [comment]
From my test(binary is build from main branch with make build-release) on EC2, it panicked(exit with no error in the log) every time.

**Comment by b41sh** [comment]
ok, I will add more test
