### ISSUE TITLE
bug:  inconsistency result between mysql handler and http handler

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.23-nightly

### What's Wrong?

When I try to use http handler to run stateless tests, I encountered some issues.
Some of them should be fine, like data inconsistency `2` vs `2.0` etc,
But others are pretty strange. (where I marked TODO in the .sql file.
I only tested `sql suffix file` in statelss tests in `standalone` mode, and I have wrapped the whole unfinished tests dir as supplement material

### How to Reproduce?
unzip the following directory

[debug.tar.gz](https://github.com/datafuselabs/databend/files/8526501/debug.tar.gz)

In the supplement material, run the following command
**NOTICE:**
should install sqlparse for multi-query splitting
```python
pip install sqlparse
```

```bash
./databend-test --mode 'standalone' --run-dir 0_stateless --suites suites --client http 
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
As I mentioned before， http handler did not share a  single session, it will create separated session  per query.

https://github.com/datafuselabs/databend/issues/4955#issuecomment-1103536420

So `SET max_threads=16;` will not work for the latter query.

**Comment by ZhiHanZ** [comment]
> As I mentioned before， http handler did not share a single session, it will create separated session per query.
> 
> [#4955 (comment)](https://github.com/datafuselabs/databend/issues/4955#issuecomment-1103536420)
> 
> So `SET max_threads=16;` will not work for the latter query.

yep, I encountered such issue in stateless test, and I think we should separate a directory to test http handler functionalities.

**Comment by youngsofun** [comment]
http handler support session by carrying a sessionid，
we can use it in a client，I am working on it

**Comment by sundy-li** [comment]
I suggest to pass the settings inside the http params like ClickHouse did.

**Comment by youngsofun** [comment]
for HTTP, either client or server need to keep the session info between request.



for client-side session

1. better used with a `client/driver` instead of bear HTTP
2. for Completeness. need to properly handle commands like `SET max_threads=16;` `use database`
    - presto: server return `SET max_threads=16` back to the  client,  presto client update the settings locally
3. may have some limitations:  depends on server impl,  some state have to be kept on server-side, or maybe too heavy to recreate for each request.
4. a big advantage of it is no need to route to the same server which memorizes the session state.

compare with it, the server-side session is more comfortable for clients. but

1.  the `client` still need some extro work: retrieve the session_id. 
2.  server have burden to tracking sessions, and timeout idle ones.
3.  need to route to the same server,  not extra problem if result fetching needs to be route to the same server.

currently, HTTP handler interface is designed to be able to use both, client can choose either to reuse the `session`, or create a `session` each time. the `session` corresponds to the `Session` struct in code. 
 mixing them may cause ambiguity，respect the  `SET max_threads=16;` or  http params?

I will add the settings field in the request JSON first, just as the `db` field current exists , so at least make it easy run one sql with settings in one request.

**Comment by youngsofun** [comment]
error category and examples


# 1.  mysql special,  maybe expected
---

##  MySqlDialect


    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql

## mysql-srv


    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/07_use/07_0000_use_database.sql
-- {ErrorCode 1003, but it not work, because it's trimed in opensrv-mysql}
USE not_exists_db;


# 2. display may (or may not) need to handle somewhere
----

## Nan

select avg(number) from numbers_mt (10) where 1 = 2;

-Nan
+Null

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0000_function_arithmetic.sql

## float display

SELECT 20 DIV 5;
-4
+4.0

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0002_function_cast.sql

  /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0013_function_running_difference.sql


##  datetime display

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0012_function_datetimes.sql


create table t(d32 datetime, d64 DateTime(3));
insert into t values('2022-04-02 15:10:28', '2022-04-02 15:10:28');
insert into t values('2022-04-02 15:10:28.221', '2022-04-02 15:10:28.221');
select * from t order by d64;

-2022-04-02 15:10:28.221000     2022-04-02 15:10:28.221
+2022-04-02 15:10:28    2022-04-02 15:10:28

## Escape

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0023_function_strings_quote.sql

-a\\0b 
+a\0b // fixed if use repr(s) instead of str(s) in python test

# 3.  need fix
---

##  json value in json (decoded recursively  by python)

SELECT parse_json('"ab"')::array;
-["ab"]
+['ab']

SELECT parse_json('{"a":1,"b":2}')::object;
-{"a":1,"b":2}
+{'a': 1, 'b': 2}.  // "data”:[[{“a”:1,”b”:2}]],   decoded by python

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0049_function_semi_structureds_check_json.sql

parse_json


    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.sql

get_path



# only need to fix databend-test

## user


    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0016_function_context.sql

-'default'@'127.0.0.1’  // mysql —user default 
+'root'@'127.0.0.1'


##  sqlparser return sql with comments

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/01_system/01_0002_system_query_log.sql

select count(1) from system.query_log where query_text='select count(*) from tbl_01_0002 where a > 1' 


    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/02_function/02_0000_function_aggreate_on_empty.sql


## test result display

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/06_show/06_0001_show_create_table.sql

diff dealing with \n when print

    /Users/yangxiufeng/work/databend/tests/suites/0_stateless/06_show/06_0003_show_settings.sql

diff dealing with \n when print

**Comment by youngsofun** [comment]
most of these are about field display.  maybe controlled by one of 

1. server, maybe in settings?
2. driver
3. cli which uses the driver


also affected by the transport format
driver may need do some  work to translate field value to language variables , referring to the schema 

- binary
   -  arrow : one-way mapping？
   - one-way mapping:   mysql, clickhouse
- others: 
    - json
    - csv

**Comment by youngsofun** [comment]
@ZhiHanZ  most of them do not cause a big problem, I think we can just do some necessary `fix impl`, and work directly on the new stateless test later

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ  most of them do not cause a big problem, I think we can just do some necessary `fix impl`, and work directly on the new stateless test framework later

LGTM， I think float or NaN issues could be resolved by a well designed test framework

**Comment by ZeaLoVe** [comment]
I found another， SELECT Null + 1, Null - 1, Null * 1, Null / 1;  
Mysql handler get ok：
+------------+------------+------------+------------+
| (NULL + 1) | (NULL - 1) | (NULL * 1) | (NULL / 1) |
+------------+------------+------------+------------+
|       NULL |       NULL |       NULL |       NULL |
+------------+------------+------------+------------+

Http handler get error：
"code": 1010,    ->  BadDataValueType(1010)
"message": "Ops is not support on datatype: Null"

cc @sundy-li @youngsofun

**Comment by youngsofun** [comment]
move to https://github.com/datafuselabs/databend/issues/4976
