### ISSUE TITLE
Feature:  Considering add synchronous catalog/metaservice api

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5287]
**Summary**

Description for this feature.

For Now:

1. Parser is in sync mode
2. PlanParser is async mode,  because Analyzer/Binder needs catalog async API, user manager async API  (in server handler's runtime).
3. Executor is in async mode   (in context runtime)

We need to parse raw SQL into Expression in meta deserialization.

Consider query `show functions`

`ShowFunctionsInterpreter` will rewrite the SQL and call  async `PlanParser::parse`, so I think it may lead to the query hang (not 100% sure about it, maybe it's bug of metaservice).

Currently, it's found in pr: #5260 

Related #5283

**Comment by leiysky** [comment]
We were of the same mind at the same time. 🤣

**Comment by sundy-li** [comment]
`Show roles` will call async user api if cache miss happens.


There is a temporary way to avoid calling async API inside different runtime:

We should avoid calling the planner parser inside the interpreter, so remove all `ShowXXX` planners, and rewrite the SQL during the planner parser & analyzer stage.   @BohuTANG  what do you think?

**Comment by BohuTANG** [comment]
@sundy-li 

It's hard to guarantee that someone will write such code again, so let's see how to solve it better.

**Comment by sundy-li** [comment]
Introduce a global runtime, query will send the request to the channel and block wait for the result.

**Comment by BohuTANG** [comment]
How about calling catalog with sync block_on in a global runtime?

**Comment by BohuTANG** [comment]
Can we temporarily disable `stateless-test` CI on MacOS? @Xuanwo

**Comment by BohuTANG** [comment]
> Can we temporarily disable `stateless-test` CI on MacOS? @Xuanwo

Disabled it in https://github.com/BohuTANG/datafuse/commit/40822860a2722a066d95212409a44afda19551d8, and merged to the main branch.

**Comment by Xuanwo** [comment]
> > Can we temporarily disable `stateless-test` CI on MacOS? @Xuanwo
> 
> Disabled it in [BohuTANG@4082286](https://github.com/BohuTANG/datafuse/commit/40822860a2722a066d95212409a44afda19551d8), and merged to the main branch.

We need to comment checks in [production.yml](https://github.com/datafuselabs/databend/blob/main/.github/workflows/production.yml) too.

**Comment by dantengsky** [comment]
About sync catalog API :

How about introducing another "pass", let's say, 
 - right after the statement is parsed but before "analyzed"
 - traverses the statement, and collects all the objects to be resolved by catalog
 
so that the binder,  type checker, etc. can work in the sync context.

~~~
impl PlanParser {

    pub async fn parse(ctx: Arc<QueryContext>, query: &str) -> Result<PlanNode> {
        let (statements, _) = DfParser::parse_sql(query, ctx.get_current_session().get_type())?;
        
         // an extra pass, to collect all the catalog enties to be resolved
  
         // - traverse the statement
         let mut statement_visitor = CatalogEntriesCollector::new(); 
         statement_visitor.visit(statement);
         
         // - resolve them, async fn call
         let resolved_entities = catalog_ext::resolve(statement_visitor.catalog_entities_to_be_resolved).await?; 
         
        // put the `resolved` in some context, or just pass it on
        PlanParser::build_plan(statements, ctx, /*extra arg*/resolved_entities ).await
    }


  ...
  
}
~~~

At least, for CTE statements, the `statement_visitor` seems to be non-trivial (and may have to do some duplicated works of later ”passes")

**Comment by leiysky** [comment]
> How about introducing another "pass", let's say,

This works, but the problem here is that we don't know if the `Catalog` would be accessed in a synchronous context in the future. If that does happen, we have to add an extra async resolution pass, and find a `async` context to execute it, which is a disaster.

Maybe we can have a daemon catalog thread to handle the request?
