### ISSUE TITLE
Improvement(ci): A simple ,fast, manual control test workflow is required 

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#5876]
Current workflow of developing and production do too much thing , takes a long time to run about an hour .
Maybe we can offer a manual control workflow for developers run tests in their forked repo? Only keep steps: build、run、test,
as we did locally.

support: arch 、branch to test 、which test to run and so on。

**Comment by Xuanwo** [comment]
In fact, it's the fastest workflow we can archive now.

![image](https://user-images.githubusercontent.com/5351546/172970051-49d8848c-dd90-4b70-9e97-603109b800d3.png)

Take a normal PR (developing) build an example.

- In check, we will do `clippy` and `toml` check which is **required**.
- In build, we will do `build` and use the generated artifacts to do stateless/stateful tests, which is **required**.
- In unit tests, we will do unit tests, which is **required**

Most of them happened at the same time, we are limited by runner's concurrency and performance.

The biggest bottleneck now is:

![image](https://user-images.githubusercontent.com/5351546/172970331-74b8433e-0c47-48bd-bdfb-badb016c3712.png)

- macOS build: our self-hosted runners' framework doesn't support macos, we have to deploy by ourselves.

![image](https://user-images.githubusercontent.com/5351546/172970369-1971612e-ec58-4996-9e58-d46908733020.png)

- hive build: Maybe we can move this build to our self-hosted runner too.

---

I don't know if it's a good idea to move macOS out of our workflow.

**Comment by sundy-li** [comment]
We need faster build!

**Comment by Xuanwo** [comment]
> hmmm ... What I actually mean is that a pipeline is needed to allow developers to run through the core process at high speed in their own branch so that they don't have to spend time waiting for pr checks.

The whole time is decided by the longest block in each part, please don't sum them up.

In our case, the total time is:

![image](https://user-images.githubusercontent.com/5351546/172973145-962a1304-da9d-4f54-9739-dc1eeeb54957.png)

To make our CI faster, we need to fix the bottleneck instead of adding a new simpler workflow (because there is no such thing :laughing: )

**Comment by Xuanwo** [comment]
I start a proposal for this issue: https://github.com/datafuselabs/databend/discussions/5880

Welcome for any comments!

---

> Maybe not need to build every time, just build when codes or something else changes. Commits only fix use cases not need to build.

Make sense to me, but I don't how to implement this. 

Because databend will build `databend-query` and `databend-meta`, every line changed in `common/` could result in changes in our query. So it's not acceptable to only build/test the crate itself.

Make everything worse, github doesn't support sharing artifacts between workflows. So we have to build the binary everytime.
