### ISSUE TITLE
bug: select return nothing but retry will get results

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#5973]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.82-nightly 

### What's Wrong?

![WtQ54VJNym](https://user-images.githubusercontent.com/10904090/173540441-dd595519-39d0-4309-97ff-37f5e65dea9e.jpg)

cc @sundy-li  

### How to Reproduce?

Easy to reproduce in the process of testing a large number of select statements.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZeaLoVe** [comment]
cc @youngsofun  still exists in the build v0.7.86-nightly, maybe not the same problem.

**Comment by ZeaLoVe** [comment]
Fixed in the build v0.7.86-nightly, close it,

**Comment by ZeaLoVe** [comment]
[1_1_select.txt](https://github.com/datafuselabs/databend/files/8907448/1_1_select.txt)

Still exists when running the logic test with this case. cc @youngsofun

**Comment by youngsofun** [comment]
@zhang2014 

both http handler and mysql handler fail because some query should return some rows but did not.
these are flaky test,  seem not related to a Specific case
I guess it may be a bug of pipeline? can you help fixing it?

unzip [select_cases.zip](https://github.com/datafuselabs/databend/files/8908722/select_cases.zip)
 in `tests/logictest/suites/gen `
replace  `tests/logictestlogictest.py` with  [logictest.py.txt](https://github.com/datafuselabs/databend/files/8909890/logictest.py.txt)

```
export DISABLE_HTTP_LOGIC_TEST=1
cd tests/logictest
python ./main.py ".*select.*.test"
```

**Comment by zhang2014** [comment]
@youngsofun Ok. I will try to fixes it.

**Comment by ZeaLoVe** [comment]
@zhang2014 Any progress？

**Comment by zhang2014** [comment]
Sorry, I worked on other tasks before. Now let's come back here.
