### ISSUE TITLE
numbers table performance with new planner v2

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6200]
**Summary**

From my local benchmark, performance is 2x better than the new planner_v2.

## How to test

```
SELECT avg(number) FROM numbers_mt(100000000000);
```

### Old Planner V1
```
MySQL>  set enable_planner_v2=0;
mysql> SELECT avg(number) FROM numbers_mt(100000000000);
+------------------+
| avg(number)      |
+------------------+
| 9323559.74711512 |
+------------------+
1 row in set (6.27 sec)
```

![image](https://user-images.githubusercontent.com/172204/175492978-e600ff2f-12fc-4d9b-b99f-d9ebb2da023f.png)

### New Planner V2
```
mysql> set enable_planner_v2=1;
mysql> SELECT avg(number) FROM numbers_mt(100000000000);
+------------------+
| avg(number)      |
+------------------+
| 9323559.74711512 |
+------------------+
1 row in set (10.61 sec)

```

![image](https://user-images.githubusercontent.com/172204/175493019-49df3f82-c264-4c0f-8541-426dcd1e8b54.png)

**Comment by BohuTANG** [comment]
cc @zhang2014 @leiysky

**Comment by leiysky** [comment]
It's expected.

The reason is that we are using a `ColumnID` to identify columns in `DataBlock`s when running query with new planner, which is diffenrent from the legacy planner. For now, we resolve this by adding a `ProjectTransform` right after `SourceTransform` to remap the column names into `ColumnID`s.

This overhead is low, but will become significant for simple queries like `select * from numbers(n)`.

We can eliminate the extra `Project` after completely migrated to new planner.
