### ISSUE TITLE
Consider renaming project. DataFuse is too similar to DataFusion.

### ISSUE THREAD

**Issue by andygrove** [datafuselabs/databend#654]
This project appears to have similar goals to Apache Arrow DataFusion, contains code from DataFusion, and has a very similar name. 

The names "DataFuse" and "DataFusion" only differ by a few characters and this could cause confusion about the relationship between these projects.

On behalf of the Apache Arrow DataFusion community, who have put a lot of work into building the DataFusion software and brand over the past three years, I respectfully ask that you consider renaming this project.

**Comment by l1t1** [comment]
your username andygrove is too similar with former CEO of intel

**Comment by BohuTANG** [comment]
Hi @andygrove 

We have lot of respect and admiration for [arrow-rs](https://github.com/apache/arrow-rs) and [data-fusion, former in arrow/datafusion](https://github.com/apache/arrow-datafusion), it makes that Rust is for big data, thank you very much @andygrove and the community!

datafuse contains some codes from datafusion (mainly [datavalues](https://github.com/datafuselabs/datafuse/tree/master/common/datavalues/src)), but We think it's all following the apache licenese, so please correct me if we doing anything wrong:
https://github.com/datafuselabs/datafuse/blob/master/website/datafuse/docs/policies/notice.md

datafuse is a DBMS(compute and storage), we refer to the architecture of ClickHouse, we are positioned as the next generation of ClickHouse, which is not the same as datafusion.

For the name, we like datafusion a lot and of course datafuse.
Name is cheap, what matters is the code and what problem it solves!

**Comment by andygrove** [comment]
Hi @BohuTANG and thanks for the response. 

Yes, the use of the DataFusion code is absolutely fine as far as I have seen. The issue is just the confusion with a very similar project name. The projects are similar in that they both implement query engines in Rust based on Apache Arrow format.

DataFuse looks like a really interesting project but in my opinion, I think it would be better to use a name that differentiates it from DataFusion.

**Comment by onzo-bryanfeeney** [comment]
> Name is cheap, what matters is the code and what problem it solves!

If the name is cheap it should cost you nothing to change it, so why not make the change?

**Comment by BohuTANG** [comment]
> > Name is cheap, what matters is the code and what problem it solves!
> 
> If the name is cheap it should cost you nothing to change it, so why not make the change?

Hi!
In terms of projects name, the datafuse project has an earlier name than datafusion.
datafuselabs/datafuse(Mar 27 2021): [b335630](https://github.com/datafuselabs/datafuse/commit/bfa0bfb28ade1685987148e57c65dbaa976c89a3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
arrow-datafusion(04 May 2021): https://arrow.apache.org/blog/2021/05/04/rust-dev-workflow/

So, we just keep using the name.

**Comment by Dandandan** [comment]
@BohuTANG 

That's incorrect.

DataFusion is a project that was started end 2016 / beginning 2017 by @andygrove with that name.

https://github.com/andygrove/datafusion/commits/master?before=219ca3f61f0d751779b4f30c02aa5fdcf8a40d12+385&branch=master

Early 2019 it was donated to Apache Arrow already:

https://arrow.apache.org/blog/2019/02/04/datafusion-donation/

**Comment by BohuTANG** [comment]
> @BohuTANG
> 
> That's incorrect.
> 
> DataFusion is a project that was started end 2016 / beginning 2017 by @andygrove with that name.
> 
> https://github.com/andygrove/datafusion/commits/master?before=219ca3f61f0d751779b4f30c02aa5fdcf8a40d12+385&branch=master
> 
> Early 2019 it was donated to Apache Arrow already:
> 
> https://arrow.apache.org/blog/2019/02/04/datafusion-donation/

Thanks for the correction.
Who have a better name ? :thinking:

**Comment by gauss1314** [comment]
Hi @BohuTANG ,how about Basefuse ?

**Comment by andygrove** [comment]
I think that there are plenty of smart and creative people here that can help with coming up with a name. It would be helpful to know the motivation/meaning behind the name DataFuse.

**Comment by BatmanAoD** [comment]
Why was the previous name (as seen in that commit from March), FuseQuery, changed?

**Comment by l1t1** [comment]
try datamix？

**Comment by BohuTANG** [comment]
@andygrove @BatmanAoD @l1t1 
Hi！
There are some challenges here, the project datafuse creator company also called datafuse, it's hard for us to change it.
At present, we are fully focused on product development, the name should be considered in the long run.

**Comment by houqp** [comment]
if you are going to change the project name eventually, it's better to do it sooner than later so you can build the brand. Changing the name later after will impact you negatively on SEO and marketing etc.

**Comment by BohuTANG** [comment]
> Why was the previous name (as seen in that commit from March), FuseQuery, changed?

FuseQuery is one part of Datafuse, it's a query engine:
https://github.com/datafuselabs/datafuse/tree/master/fusequery

Datafuse is a DBMS, it consists of several components:
1. FuseQuery -- distributed query engine
2. FuseStore -- distributed storage engine
3. FuseCLI -- a deploy and management all in one tool for Datafuse

**Comment by andygrove** [comment]
Given that all the parts start with Fuse, I would probably start the product name with Fuse as well. The most obvious choices to me would be:

- FuseDB
- FuseData
- FuseBase
- FuseIO
- Fused

I think the company name is less of a concern to the community than the product name, but that's just my opinion.

**Comment by junli1026** [comment]
How about DataForge, which has the same init with DataFuse (DF). Thus we can keep use the df prefix in the code :)

**Comment by BohuTANG** [comment]
@junli1026 Thank you.
As it stands now, datafuse has some (minor) popularity, we're not considering changing the name and we don't want to waste any more time on this topic, this issue will be closed this weekend.
If you have any ideas, feel free to open a new one.
Thanks all.

**Comment by BatmanAoD** [comment]
@BohuTANG For what it's worth, this seems pretty underhanded to me. It seems clear that you never intended to change the name, and that your request for suggestions was not sincere. The fact that the name is popular is, if anything, an indication that you probably have benefited from choosing a name so close to DataFusion, which I am still not convinced you didn't know you were doing.

**Comment by BohuTANG** [comment]
@BatmanAoD 

That's not true, datafuse team is under pressure because of this ISSUE, we have discussed it many times and we don't want to continue.
The name `datafuse` does not harm any community and our team will not do so, and not intended to leverage anyone's halo, if so please let us know.

So why are we currently struggling with the name? 
Anyway, The name we believe is not wrong and does not harm others, if so please let us know!

**Comment by Dandandan** [comment]
@BohuTANG

In my opinion, keeping the name as `datafuse` is harmful, both for the future of DataFusion and DataFuse communities and product, as the names are too similar for very similar projects (sharing a large portion of inspiration, dependencies and even some code reuse from DataFusion) and leads to confusion.

The current "resolution" (not to change the name) is disappointing to me, given the discussion and facts presented earlier and discussed alternatives.

**Comment by PsiACE** [comment]
Hello everyone. It's great to see your suggestions in terms of name changes.

But I'd like to say a few extra things.

1. we are not trying to get into the light of datafusion. Despite the similarity in name, we are not trying to divide and harm the community. We are trying to actively contribute to upstream projects as well, and we are contributing to the prosperity of the entire ecosystem. It would be unfair to stereotype us as doing something harmful just because we have a similar name.

2. we recognise the similarities with datafusion, but we are doing something different and trying to do it well. we don't want to get caught up in controversy, which would make everyone feel bad. We had some serious discussions about changing the name, but it was difficult. On the one hand, we have put just as much effort into building the brand; on the other hand, if we give up datafuse today because of arrow-datafusion, will we need to give up even more tomorrow?

I believe that the Rust community is inclusive and full of goodwill. I also hope you will give us some time to work through these things. datafuse and arrow-datafusion are like twins, we trust and appreciate arrow-datafusion's efforts and try to work side by side with them. Let's put aside the name debate for a moment and work together to build a great era of data.

Good luck, Rustaceans, the friendly community blessed us.

**Comment by sundy-li** [comment]
> It would be helpful to know the motivation/meaning behind the name DataFuse.

When we started this project at the beginning, its name is 'fuse-query'.  But when we noticed that its goal is not just a query engine but a data warehouse, so we changed it into `Datafuse`, the motivation is really not related to datafusion. We did not notice it's very similar to datafusion until this issue is opened.

> It seems clear that you never intended to change the name

We were also searching for an easy way to rename it again. But due to many irresistible reasons,  currently, it's really very hard for us to change into another name.

**Comment by l1t1** [comment]
if rename the product, the company name and domain name need to be renamed too. 
but great product doesn't relay on name only.
eg.  after tencent renamed oicq to qq, it is much more successful than icq now.

**Comment by houqp** [comment]
I have seen many contributions from the datafuselabs team, especially @sundy-li and @BohuTANG, to upstream projects like arrow2, sqlparser-rs and datafusion. Based on my observation so far, I do believe the team has good intention and are good citizens to the open-source community. The naming issue is perhaps due to language barriers. In English, `datafusion` is really similar to `datafuse`, so it will definitely cause confusions to your potential customers outside of China.

> Anyway, The name we believe is not wrong and does not harm others, if so please let us know!

@BohuTANG I think all the other comments in this thread is the community letting the team know that the name does harm both sides :) It not only confuses datafuselabs customers, but also paints a bad look to the company as demonstrated by some of the comments in this thread.

> if we give up datafuse today because of arrow-datafusion, will we need to give up even more tomorrow?

@PsiACE I think you are over thinking this :) The community is only asking for a rename that will benefit both sides. That's it. I would personally stand up and help defend other unreasonable requests if any comes up. But I really doubt you would get any in the future.

> I also hope you will give us some time to work through these things
> We were also searching for an easy way to rename it again. But due to many irresistible reasons, currently, it's really very hard for us to change into another name.

I am really approaching this from datafuse the companpy's point of view. If the company plans to rename the product in the future anyway, then doing it sooner than later will cause a lot less chaos. As @andygrove mentioned earlier, the community is not being unreasonable and ask the company to do a full rename, but just renaming the datafuse project/product to something else that would benefit both sides. I also agree with @andygrove that `datafuselabs` is a perfectly fine name for the company.

If the company really cannot change the project name due to irresistible reasons, I think it would be beneficial to share that with the community to end the discussion. If those reasons are really irresistible, I believe the community will understand and move on. To be fair, extra work of changing the domain name is not a very convincing argument.

> but great product doesn't relay on name only.

@l1t1 I fully agree with you, that's why I think renaming datafuse to a more distinct name now will not harm the product and will in fact benefit it more in the long run. It would even benefit the product in the short run because rebranding a product is a good opportunity for an other round of marketing push to gain more publicities.

> eg. after tencent renamed oicq to qq, it is much more successful than icq now.

In my opinion, qq is very different compared to oicq because they don't share majority of the prefix prefix. Like I mentioned earlier, perhaps this is due to language barrier. A better comparison would be `qq` v.s. `qqs` or another company launched a product called `datafuser` that does similar things compared to `datafuse`.

**Comment by sundy-li** [comment]
Hello everyone, please give us some time, we are trying our best to searching for better solutions again, hope the better decision will be made public in days.

**Comment by sundy-li** [comment]
Hello everyone, here comes a good news:

**We are going to change to a new name!**

Our team has discussed this issue many times internally for months. Although the process was very tortuous, we finally reached an agreement.

The main reason is that, as @andygrove said, keeping the name `datafuse` will cause misunderstandings in the community.This is detrimental to both repos and the entire community. Sorry that this long-thread issue has bothered my friends from the community a lot.

Now, the process of renaming the project has started.Rebranding requires a lot of process work (domains, trademark registration, documents, codes ..), but this is all worth it, I expect it can be done ASAP.

After the new name is determined, we will make it public ASAP. No matter what the new name is, we promise the product will keep 100% free, open-source  and community friendly. Thank @andygrove for pointing out the problem kindly, so that many potential risks can be prevented.

We also thank many community friends for their suggestions, especially @Dandandan, @houpq, @BatmanAoD, @junli1026, @gauss1314, @l1t1  etc. 

Lastly, the open-source ecosystem needs everyone's efforts to be better. As `datafuse` noted in README, `Datafuse is inspired by ClickHouse and its computing model is based on apache-arrow.`

It's already standing on the shoulders of giants. We are also proud of that,  `datafuselabs` will continue to embrace the whole open source community and contribute back to upstreams, especially the big data projects under the rust ecosystem.

**Best wishes, may you have a good weekend.**

**Comment by kingice** [comment]
> > Name is cheap, what matters is the code and what problem it solves!
> 
> If the name is cheap it should cost you nothing to change it, so why not make the change?

can't agree more!In chinese like :  不要搬起石头砸自己的脚，用自己的话堵自己的嘴。

**Comment by kingice** [comment]
> > @BohuTANG
> > That's incorrect.
> > DataFusion is a project that was started end 2016 / beginning 2017 by @andygrove with that name.
> > https://github.com/andygrove/datafusion/commits/master?before=219ca3f61f0d751779b4f30c02aa5fdcf8a40d12+385&branch=master
> > Early 2019 it was donated to Apache Arrow already:
> > https://arrow.apache.org/blog/2019/02/04/datafusion-donation/
> 
> Thanks for the correction.
> Who have a better name ? 🤔

Why not fusedata？

**Comment by BohuTANG** [comment]
@kingice Hi!
We have considered all the names have provided, this is a difficult choice as it involves trademarks as well as domain names etc.
Thank you

**Comment by andygrove** [comment]
Thank you @sundy-li @BohuTANG and everyone else involved! This is really great news for the open-source communities involved. I know this caused additional work for your team and I am very grateful that you took this on and resolved the issue.

**Comment by andygrove** [comment]
Resolved by https://github.com/datafuselabs/databend/pull/1816

**Comment by BatmanAoD** [comment]
> Resolved by #1816

I believe you mean #1814!

Thanks again to @sundy-li and @BohuTANG.

**Comment by houqp** [comment]
Thank you @BohuTANG @sundy-li and the rest of the datalabs team for all the efforts you put in :) Go Databend!

**Comment by Dandandan** [comment]
Thank you! Databend sounds great 😁
