### ISSUE TITLE
Add compat test for metadata objects

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6567]
**Summary**

similar issue: https://github.com/datafuselabs/databend/issues/6557

the metadata objects are the metatypes stored inside metasrv, but the data schema is only known to databend-query.

on changing the metatypes definitions, there's possibility to break up compat in both backwards and forwards manner:

like:

1. create user/stage/udf in current version
2. read the user/stage/udf in the previous version

and:

1. create user/stage/udf in the previous version
2. read the user/stage/udf in the current version

**Comment by BohuTANG** [comment]
@drmingdrmer for some suggestions on the CI.

**Comment by drmingdrmer** [comment]
The compatibility between rust-types and protobuf is mainly about these two versions:
https://github.com/datafuselabs/databend/blob/28598be16cbf4dffa3c6b9fa62d62421c3f422e2/common/proto-conv/src/lib.rs#L33-L34

To ensure compatibility, the best practice would be: every time to change the rust types:
- 1. Add a serialized protobuf message of the current `VER`(e,g. `VER=3`) rust types to the unit test, as it already did:
https://github.com/datafuselabs/databend/blob/9f42accfee63ea9eb8c57689f1383c01d136a7c3/common/proto-conv/tests/it/user_proto_conv.rs#L203-L218

- 2. Increment the `VER`, e.g., let `VER` be `4`. Add a test to load the old version serialized data from step 1.

When an old version of rust types is no longer needed, increment `MIN_COMPATIBLE_VER` and delete the test data and case.

BTW, if necessary, it would be better to introduce more than one pair of `VER, MIN_COMPATIBLE_VER` for different kinds of metadata, e.g. `SCHEMA_VER` and `SCHEMA_MIN_COMPATIBLE_VER` for data types used by `SchemaApi`, `USER_VER` and `USER_MIN_COMPATIBLE_VER` for data types used by user related APIs. Since different kinds of meta types may evolve independently.
