### ISSUE TITLE
Allows loading of test suites from external sources

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#6701]
**Summary**

Now we have to maintain a large number of test files in the repo. And it would take a lot of time to run a large number of tests at once.

Is it possible to look like the following?

- Keep a core test suite in this repo that covers our main functions and capabilities.
  - `make sqllogic-test`
  - ci for debug
- Allows loading (cloning) of compliant test suites from external repositories. (ydb/ck/crdb)
  - ci for release (we can decide on the frequency of execution.)

**Comment by flaneur2020** [comment]
I think directly referencing test cases from other repositories may hard to maintain because the test cases format may differ between projects, and they might change as their will, and we may choose to skip some test cases which do not met our needs.

maybe a middle ground is make a seperate databend-contrib-testcases git repository (like the LTP project https://github.com/linux-test-project/ltp to linux kernel?), it can be controlled or extended by our engineers.

**Comment by PsiACE** [comment]
> maybe a middle ground is make a seperate databend-contrib-testcases git repository, it can be controlled or extended by our engineers.

Yes, we need to maintain a seperate databend-contrib-testcases git repository.

Of course, once external loading is allowed, our users can also customise the test suite to suit their use case.

**Comment by ZeaLoVe** [comment]
We already support --run-dir , --skip-dir , --suites to control which test will be run. This issue is not a high priority, for now, close it first, If we have a further plan, re-open it then.
