### ISSUE TITLE
New planner doesn't support creating table with field `b int default a + 666`

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6893]
```rust
let query = "\
        CREATE TABLE default.a(\
            a bigint null default 666, b int default a + 666, c varchar(255), d smallint, e Date\
        ) Engine = Null\
    ";
```

**Comment by leiysky** [comment]
This is as expected, we have discussed about this before. My suggestion is to use a generated column to implement this instead, since it's confusing if there is mutual recursion in such a context(e.g. `create table t (a int default b+1, b int default a+1)`).

My suggestion is deprecate the feature, or implement it with a formal design.

**Comment by Xuanwo** [comment]
We can remove the test case located at 

https://github.com/datafuselabs/databend/blob/4443752e7fb0237ba33146e35b7ab201e50a9819/query/tests/it/interpreters/interpreter_table_create.rs#L25-L26
