### ISSUE TITLE
Enable `strip` for releasing

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7792]
**Summary**

After applying this diff

![image](https://user-images.githubusercontent.com/5351546/191572530-bdcb54b5-59f9-4af6-a9e3-3ef3a3a321e1.png)

Our databend query's size dropped from (built by `cargo build --release`)

```shell
.rwxr-xr-x  690M xuanwo 22 Sep 01:41  databend-query
```

to

```shell
.rwxr-xr-x   93M xuanwo 22 Sep 01:36  databend-query
```

Questions:

- Why do we need `debug=1` for releasing?
- Can we enable `strip`?

Cc @PsiACE may have some ideas.

**Comment by PsiACE** [comment]
**about `strip`:**

We have used the following to reduce the size of the binary file.

```
objcopy --compress-debug-sections=zlib-gnu
```

Although strip could result in a smaller size, I'm not sure it makes sense.

**about `debug=1`:**

It keeps something for us while greatly reducing debugging information, so that we can still get useful crash information during production deployments.
