### ISSUE TITLE
Consider to remove fuse result

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9332]
**Summary**

Now fuse result is used anymore, we should remove them all:
https://github.com/datafuselabs/databend/blob/a965a31a69d8c5dc9775ca5e7d561f1d3f150192/src/query/storages/fuse/fuse-result/

**Comment by BohuTANG** [comment]
@youngsofun would like your suggestions.

**Comment by youngsofun** [comment]
Personally, I think, as a cloud database, finally we will need it to offload the result it to s3 instead of returning to HTTP handler directly,  like snowflake.
and another usage of it is result cache, which is implemented by most AP DBs.

but we can remove it for now if and add it back when need it if it is a burden of parquet-related refactoring/optimizing.

**Comment by youngsofun** [comment]
cc @flaneur2020 if you have no other plan about downloading/query_result recently, I will remove related codes

**Comment by BohuTANG** [comment]
@flaneur2020 Confirmed, the cloud does not use it anymore.
fuse-result currently interferes with the parquet block reader. Even if we do cache, we have some better ways to do it later.
Let's remove it!

**Comment by wubx** [comment]
Snowflake Query results maybe use time travel, not save a copy of the actual data.

**Comment by youngsofun** [comment]
>> Snowflake Query results maybe use time travel, not save a copy of the actual data.

maybe we are not talking about the same thing.

I  once watched a video that mentioned it specifically in 2 pages.
some BI tools are very likely to query the same SQL recently, 
it is very efficient when the overhead of saving the result is smaller than the compute overhead (filter/sort/aggr), which is a common pattern for AP.
there are many papers about this too.
