### ISSUE TITLE
Feature: Introduce bitmap to record applied rules

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#9536]
So far, we are implementing the structure `AppliedRules` with a `HashSet<RuleID>`, which is inefficient. It's possible to improve this by introducing a real bitmap data structure.

cc @dusx1981

**Comment by dusx1981** [comment]
I don't have permissions assigned to myself

**Comment by dusx1981** [comment]
As an operator, you should know which rules you can apply, so I want to add an interface to the operator: CandidateRule. When applying a rule, it intersects it with the rules in the rule set, and then applies the rule in a loop.

The management of rules should be unified and managed by category, instead of using DEFAULT_REWRITE_RULES and get_explore_rule_set to manage separately.

The advantage of this is that the rule management of HeuristicOptimizer and CascadeOptimizer can be unified, and the interface for obtaining the rule set can also be unified.

The specific implementation is divided into two steps: 

- 1: Candidaterule returns all the rules first, which is equivalent to the existing rules, but the logic is already managed uniformly. 
- 2: The candidaterule only returns the rules that it can apply.

If you agree with my idea, please confirm, I will develop and implement it later. If I disagree, I just modify the logic of the AppliedRule as suggested.

**Comment by dusx1981** [comment]
[](https://www.processon.com/view/link/63d4dfe8c12afe0cadac50de) logical arrangement about the optimizer

**Comment by leiysky** [comment]
> The specific implementation is divided into two steps:
> 
> * Candidaterule returns all the rules first, which is equivalent to the existing rules, but the logic is already managed uniformly.
> * The candidaterule only returns the rules that it can apply.

That's good. I'm looking forward to the implementation.

**Comment by dusx1981** [comment]
I wrote some code and wanted to do a coverage test, but I didn't find the test logic related to the optimizer. Is there any test logic specifically for the optimizer?

**Comment by BohuTANG** [comment]
Unit test is here: https://github.com/datafuselabs/databend/tree/main/src/query/sql/tests/optimizer

logic test we can create a new one for it :)

**Comment by dusx1981** [comment]
There are only histogram tests here, do you mean to add optimizer-related test logic here?
src/query/sql/tests/optimizer/mod.rs:
`mod histogram;`

**Comment by BohuTANG** [comment]
Right, feel free to do it:)

**Comment by dusx1981** [comment]
I moved to the database from other fields. It is a challenge for me to construct test cases for the optimizer. Give me some time and I will try.

**Comment by dusx1981** [comment]
https://github.com/dusx1981/databend，my branch and you can see the changes now.

**Comment by dusx1981** [comment]
I added a static RuleFactory:
```
// read only, so thread safe
pub static mut RULE_FACTORY: Lazy<RuleFactory> = Lazy::new(|| {
    let mut factory = RuleFactory::create();
    factory.init_rules();
    factory
});
```
and factory.init_rules() called `RuleFactory::create_rule`, but now it adds a parameter metadata, can I get a global metadata?

**Comment by sundy-li** [comment]
> can I get a global metadata?

Metadata is created by default and injects values during binder stage

```
let metadata = Arc::new(RwLock::new(Metadata::default()));
```

**Comment by dusx1981** [comment]
**I guess it is necessary for MExpr to add a reference to the Memo that contains it.**

**Comment by dusx1981** [comment]
**I'd like to confirm that mine works now, and if so, I'd like to incorporate a PR to add test cases for the optimizer next.**

**Comment by sundy-li** [comment]
Can you create a draft pr? It'll be easy to review.

**Comment by dusx1981** [comment]
Ok, tonight I'll fix the question suggested by the automation and submit a PR

**Comment by dusx1981** [comment]
[Darft pr to be reviewed](https://github.com/datafuselabs/databend/pull/10024)

**Comment by dusx1981** [comment]
I use the old code to do comparative coverage test, the test of the same branch a few days ago，Error with only one comment：
![image](https://user-images.githubusercontent.com/7598029/221070510-c2aef65d-dfca-46f5-818d-a0d7cd281310.png)
After merging branches yesterday，A timeout error occurred: 
![image](https://user-images.githubusercontent.com/7598029/221071317-037f1bd6-1994-4250-97c1-29ecf08f2a74.png)
**Is this a problem?**
