### ISSUE TITLE
bug: panic when ordering by derived field

### ISSUE THREAD

**Issue by haydenflinner** [datafuselabs/databend#9866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.9.18-nightly-e0899c0

### What's Wrong?

ORDER BY derived column is apparently not supported, similar to https://github.com/datafuselabs/databend/issues/9849
This shouldn't panic, but also is a little surprising in something going 1.0 shortly.

### How to Reproduce?

```
MySQL [db]> create table testing1(mystr string);
Query OK, 0 rows affected (0.04 sec)

MySQL [db]> select * from testing1 ORDER BY max(length(mystr) - length(replace(mystr, ',', ''))) DESC LIMIT 10;
ERROR 1105 (HY000): Code: 1068, displayText = Cannot join handle from context's runtime, cause: task 11630652 panicked.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
The sql `select * from testing1 ORDER BY max(length(mystr) - length(replace(mystr, ',', ''))) DESC LIMIT 10;` isn't right.

such as 
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/41979257/216520218-b7948587-d64a-4a7f-8d5f-cd8f0d529d05.png">

I'll add error info instead of panic. Thanks @haydenflinner
