### ISSUE TITLE
doc: add array_sort

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#9977]
@soyeric128 Please add this func into array doc.

_Originally posted by @TCeason in https://github.com/datafuselabs/databend/issues/9941#issuecomment-1426555726_

**Comment by soyeric128** [comment]
So sorry for the late response because i was in the middle of creating cloud CN documents recently and didnt have bandwidth for this until now. 
I just made a few minor fixes and updates on https://github.com/datafuselabs/databend/pull/10091 as i saw sundy already included array_sort to the documentation. 
Thank you.
